jobs:
  build:
    name: Build server
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out sources
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Build with Maven
      run: 'cd server

        ./mvnw -B verify --file pom.xml

        '
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
